### ISSUE TITLE
Azul crashes when trying to view a dataset from citygml.org 

### ISSUE THREAD

**Issue by FrankKooij** [tudelft3d/azul#2]
Unfortunately Azul version 0.5.2 from the Mac App Store crashes when you double-click on
GMLID_SO1124524_1571_4314 in the sidebar (the sixth item from the top) after unzipping and opening this file: [http://www.citygml.org/fileadmin/citygml/docs/geoRES_testdata_v1.0.0.zip](http://www.citygml.org/fileadmin/citygml/docs/geoRES_testdata_v1.0.0.zip).

**Comment by kenohori** [comment]
Thanks for the bug report. The crash is now solved and should be included in 0.5.3. The object GMLID_SO1124524_1571_4314 is an implicit geometry (which aren't yet supported in azul), so its geometry is not shown.
