### ISSUE TITLE
epsg:4979 not rendering properly

### ISSUE THREAD

**Issue by agilliland** [tudelft3d/azul#4]
when my citygml is using epsg:4979 as its CRS i see all my buildings rendering extremely tall, which makes me think Azul isn't understanding the CRS and is treating my height values (in meters) as if they were degrees?

i've tried altering the citygml to either convert the height values in meters to degrees, or do a full coordinate transformation to another CRS and everything works fine, but I want my citygml in epsg:4979

**Comment by kenohori** [comment]
> Azul isn't understanding the CRS and is treating my height values (in meters) as if they were degrees?

That's correct. azul doesn't support CRS yet, so it's treating all coordinates equally.
