### ISSUE TITLE
does Azul support rendering CityJSON v0.6?

### ISSUE THREAD

**Issue by agilliland** [tudelft3d/azul#5]
I have some data that I'm currently writing into citygml and cityjson. Azul renders my gml just fine, but when I write the same data out into cityjson v0.6 the geometries are way off.

Notes on the Azul 0.8.1 release says it supports CityJSON v0.5 so I'm unsure if there are enough deltas between cityjson 0.5 and 0.6 to cause the issues I'm seeing or not.  I'm creating both files using citygml4j.

Here's a view in Azul of the citygml:
![screen shot 2019-01-02 at 5 07 11 pm](https://user-images.githubusercontent.com/1987787/50620137-b1b66900-0eb2-11e9-9499-37af16d6cc0c.png)

Here's the strange rendering of the cityjson v0.6:
![screen shot 2019-01-02 at 5 09 02 pm](https://user-images.githubusercontent.com/1987787/50620149-bf6bee80-0eb2-11e9-80ba-7f9b5da39e92.png)

**Comment by hugoledoux** [comment]
it does support v0.6 yes (and also v0.8, nothing related to geometries has changed). The demo files should work: https://www.cityjson.org/en/0.8/datasets/  Do they?

How did you create your CityJSON file actually, just curious?

**Comment by hugoledoux** [comment]
citygml4j offers the possibility to convert CityGML to CityJSON, it works perfectly. I suggest you use this, there's an example code (https://github.com/citygml4j/citygml4j/tree/master/citygml4j-samples/src/main/java/cityjson/citygml2cityjson)

another you can do is validate your CityJSON files with the validator in [cjio](https://github.com/tudelft3d/cjio), that might catch errors you have made during the conversion.

**Comment by agilliland** [comment]
Ahh, after a little debugging and looking at the examples you provided I found that the problem was that I was losing precision on my vertices given that I'm using WGS84 and the values all have up to 6 decimal places.  Adding this line to my cityjson output factory resolved everything ...

`factory.setVerticesBuilder(new DefaultVerticesBuilder().withSignificantDigits(6));`

I'll try running the files through cjio to validate them as well but I'm a lot more confident now that the geometries are rendering properly in Azul.  Thanks for the help @hugoledoux !
