### ISSUE TITLE
No attributes shown

### ISSUE THREAD

**Issue by phiberg** [tudelft3d/azul#9]
Hi,

I am using Azul for displaying my generated CityJSON files. 

Unfortunately Azul does not show me any attributes of any given CityObject at all, neither from my own datasets nor from the example datasets provided in the CityJSON documentation. 

My version of MacOS is 10.13.6 and the latest version of Azul in the AppStore (already reinstalled it, without fixing the issue)

Kind regards

**Comment by kenohori** [comment]
Hi,

azul hasn't yet been updated for the newest versions of CityJSON. Expect a 1.0-compatible version in a few weeks 😉.
